addons:
  code_climate:
    repo_token: c75df5383c6ed506f57bd7281c1c41200a139a6847ad4c62d0371a23d457f8c6
language: ruby
rvm:
- 2.1.2
before_script:
- cp config/database.psql.yml config/database.yml
- psql -c 'create database hpi_swt2_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: QuBJASdOtLmhMDKHah0BQMQhnixU3VpLlrpuO+jyKCJJxrjkW4UksNOablawmfMos2TlwWe+ZScCd9MEkR1Zx3qw7GqDIeMEUpWpkVNz2ApTDqLde//x7XaCKrlrtDS6j7t6yQIs3Qr7Hkvah2XE3SXnJhsQ9xnBABuwCH0I60M=
  app:
    master: event-und-raumplanung
    dev: event-und-raumplanung-dev
  on:
    repo: hpi-swt2/event-und-raumplanung
  run:
    - "rake db:migrate"
    - "rake db:seed"
    - restart
