addons:
  code_climate:
    repo_token: c75df5383c6ed506f57bd7281c1c41200a139a6847ad4c62d0371a23d457f8c6
language: ruby
rvm:
- 2.1.2
before_script:
- cp config/database.psql.yml config/database.yml
- psql -c 'create database hpi_swt2_test;' -U postgres
script: 
- xvfb-run rspec
- RAILS_ENV=test bundle exec rake db:migrate
- bundle exec rspec spec/
notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: BekStuNkzLBVTxPjbAUBorYniLIXmAp2TPmcRNZG7Q5cCPmx/I7F9Hua0ABmmK4onAnB8XvU8q/tBde5CxApE46qqRMmajBF2UkY8CADhzCs3IZB8jy3IOm3Unmv5OjrbDF+uruxx5VJ/4naNWfOwtbxG0saRsG3Aic1PhwcH8w=
  app:
    master: event-und-raumplanung
    dev: event-und-raumplanung-dev
  on:
    repo: hpi-swt2/event-und-raumplanung
  run:
    - "rake db:migrate"
    - "rake db:seed"
    - restart

