admin:
  email: martina.grabs@student.hpi.de
  username: martina.grabs
  password: D=ntBl1nk
identity_url: https://openid.hpi.uni-potsdam.de/
domains: {"student.hpi.uni-potsdam.de","hpi.uni-potsdam.de","hpi.de","student.hpi.de"}

